package Entites;




/**
 * Departs generated by hbm2java
 */
public class Departs  implements java.io.Serializable {

   
    private String Depart_id;
    private String name;
    
   
    public Departs() {
    }

    public Departs(String Depart_id, String name) {
        this.Depart_id = Depart_id;
        this.name = name;
    }

    /**
     * @return the Depart_id
     */
    public String getDepart_id() {
        return Depart_id;
    }

    /**
     * @param Depart_id the Depart_id to set
     */
    public void setDepart_id(String Depart_id) {
        this.Depart_id = Depart_id;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    
}