package Entites;
// Generated Feb 1, 2017 12:10:45 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ListRole generated by hbm2java
 */
public class ListRole  implements java.io.Serializable {


     private int id;
     private String role;

    public ListRole() {
    }

    public ListRole(int id, String role) {
       this.id = id;
       this.role = role;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


