package Entites;
// Generated Jan 23, 2017 9:58:57 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * RecordStaff generated by hbm2java
 */
public class RecordStaff implements java.io.Serializable {

    private String Id;
    private String Name;
    private String Department;
    private String Email;
    private int Bonus; 
    private int Violate;

    public RecordStaff() {
    }

    public RecordStaff(String Id, String Name, String Department, String Email, int Bonus, int Violate) {
        this.Id = Id;
        this.Name = Name;
        this.Department = Department;
        this.Email = Email;
        this.Bonus = Bonus;
        this.Violate = Violate;
    }
    
    /**
     * @return the Id
     */
    public String getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(String Id) {
        this.Id = Id;
    }

    /**
     * @return the Name
     */
    public String getName() {
        return Name;
    }

    /**
     * @param Name the Name to set
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * @return the Department
     */
    public String getDepartment() {
        return Department;
    }

    /**
     * @param Department the Department to set
     */
    public void setDepartment(String Department) {
        this.Department = Department;
    }

    /**
     * @return the Email
     */
    public String getEmail() {
        return Email;
    }

    /**
     * @param Email the Email to set
     */
    public void setEmail(String Email) {
        this.Email = Email;
    }

    /**
     * @return the Bonus
     */
    public int getBonus() {
        return Bonus;
    }

    /**
     * @param Bonus the Bonus to set
     */
    public void setBonus(int Bonus) {
        this.Bonus = Bonus;
    }

    /**
     * @return the Violate
     */
    public int getViolate() {
        return Violate;
    }

    /**
     * @param Violate the Violate to set
     */
    public void setViolate(int Violate) {
        this.Violate = Violate;
    }
   

}
