package Entites;
// Generated Jan 23, 2017 9:58:57 PM by Hibernate Tools 4.3.1

import java.util.Date;
/**
 * Staffs generated by hbm2java
 */

public class Staffs implements java.io.Serializable {
    private String id_staff;
    private String name;
    private boolean gender;
    private String birthday;
    private String photo;
    private String email;
    private String phone;
    private Double salary;
    private String note;
    private String depart;
    
    public Staffs() {
    }

    public Staffs(String id_staff, String name, boolean gender, String birthday, String photo, String email, String phone, Double salary, String note, String depart) {
        this.id_staff = id_staff;
        this.name = name;
        this.gender = gender;
        this.birthday = birthday;
        this.photo = photo;
        this.email = email;
        this.phone = phone;
        this.salary = salary;
        this.note = note;
        this.depart = depart;
    }
    
    /**
     * @return the id_staff
     */
    public String getId_staff() {
        return id_staff;
    }

    /**
     * @param id_staff the id_staff to set
     */
    public void setId_staff(String id_staff) {
        this.id_staff = id_staff;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the gender
     */
    public boolean isGender() {
        return gender;
    }

    /**
     * @param gender the gender to set
     */
    public void setGender(boolean gender) {
        this.gender = gender;
    }

    /**
     * @return the birthday
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * @param birthday the birthday to set
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * @return the photo
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * @param photo the photo to set
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * @param phone the phone to set
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * @return the salary
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * @param salary the salary to set
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * @return the note
     */
    public String getNote() {
        return note;
    }

    /**
     * @param note the note to set
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * @return the depart
     */
    public String getDepart() {
        return depart;
    }

    /**
     * @param depart the depart to set
     */
    public void setDepart(String depart) {
        this.depart = depart;
    }
    
     




}


